import React from 'react';
import { useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';

// Import the markdown file directly
import socraticDiscussionMarkdown from '../markdown/socratic-discussion.md';
import roadRageMarkdown from '../markdown/road-rage.md';
import elfBowlingMarkdown from '../markdown/elf-bowling.md';

const projectData = {
  'road-rage': {
    name: 'Road Rage',
    description:
      'Inspired by the classic Road Rash game of the 90s, this project aims to keep the same gameplay mechanics, the same humor and the same Grudge theme, while adding modern features like 4K resolution sprites, multiplayer and cloud-saving.',
    markdown: roadRageMarkdown
  },
  'socratic-discussion': {
    name: 'Socratic Discussion',
    description:
      'This innovative project aims to create a new sub-genre in gaming, specifically focused on Debating.',
    markdown: socraticDiscussionMarkdown,
  },
  'elf-bowling': {
    name: 'Elf Bowling',
    description:
      'Inspired by the classic Elf Bowling game of the 90s, this project aims to keep the same gameplay mechanics and humor, while adding modern features like 4K resolution models, multiplayer and cloud-saving.',
    markdown: elfBowlingMarkdown,
  },
};

const ProjectInfo = () => {
  const { projectId } = useParams();
  const project = projectData[projectId];

  const styles = `
    .content-projectinfo {
        background-color: #fff;
        padding: 40px;
        border-radius: 12px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 100%;
        max-width: 600px;
        margin: 40px auto;
        color: #333;
    }

    /* Styles for elements directly within content-projectinfo or generated by ReactMarkdown */
    .content-projectinfo h1,
    .content-projectinfo h2,
    .content-projectinfo h3,
    .content-projectinfo h4,
    .content-projectinfo h5,
    .content-projectinfo h6 {
        text-align: center; /* Apply to all markdown headings */
        margin-bottom: 30px;
        margin-top: 20px; /* Add some top margin for headings */
    }

    .content-projectinfo p {
        font-size: 1.1rem;
        line-height: 1.6;
        margin-bottom: 1em; /* Add some spacing between paragraphs */
    }

    .content-projectinfo a {
        color: #63b3ed; /* Keep link color for markdown links */
        text-decoration: none;
        transition: color 0.3s ease;
    }

    .content-projectinfo a:hover {
        color: #4299e1;
    }

    /* Style for the Contact Us link specifically if it's the only one you want styled like a button */
    .content-projectinfo p a[href="/contact"] {
        display: inline-block;
        margin-top: 20px;
        background-color: #63b3ed;
        color: white;
        padding: 12px 24px;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s ease;
        text-align: center;
    }

    .content-projectinfo p a[href="/contact"]:hover {
        background-color: #4299e1;
    }

    .content-projectinfo strong {
        font-weight: bold; /* Ensure bold text is actually bold */
    }

    .content-projectinfo em {
        font-style: italic; /* Ensure italic text is actually italic */
    }

    .content-projectinfo hr {
        border: 0;
        height: 1px;
        background: #ccc;
        margin: 40px 0;
    }
  `;

  if (!project) {
    return (
      <>
        <style>{styles}</style>
        <div className="content-projectinfo">
          <h1>Project Not Found</h1>
          <p>The requested project could not be found.</p>
        </div>
      </>
    );
  }

  return (
    <>
      <style>{styles}</style>
      <div className="content-projectinfo">
        {project.markdown ? (
          <ReactMarkdown 
            components={{
              a: ({ node, ...props }) => (
                <div style={{ textAlign: 'center' }}>
                  <a className="submit-button" {...props} />
                </div>
              ),
            }}
          >{project.markdown}</ReactMarkdown>
          ) : (
          <>
            <h1>{project.name}</h1>
            <p>{project.description}</p>
          </>
        )}
      </div>
    </>
  );
};

export default ProjectInfo;