baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
# My params
city = "Charlotte"
trade = "Plumbing"
isLicensed = true
isInsured = true
isBonded = true
phone = "(704) 555-1234"
email = "info@charlotteplumbers.com"
company = "Charlotte Plumbing Pros"

[markup.goldmark.renderer]
unsafe = true
